name = "ssbjr-landingpages"
main = "workers-site"
compatibility_date = "2025-10-11"

# Substitua pelos IDs/nomes da sua conta
account_id = "<CLOUDFLARE_ACCOUNT_ID>"
project_name = "ssbjr-landingpages"

[site]
bucket = "./out-pages"
entry-point = "workers-site"
